### ISSUE TITLE
regarding installation of framework

### ISSUE THREAD

**Issue by dhanz123** [SDN-Security/TENNISON#2]
the developer guide for the installation of the framework is confusing so if you could provide a document with step by step procedure on how to install the framework. i am having issues regarding installation of the mininet.

**Comment by lyndon160** [comment]
Hi Dhanz,

For the installation of mininet I highly recomend following their own guide to install as it is kept upto date.

http://mininet.org/download/

This is also the case if you want to install ONOS. Follow their developer's guide. Though I only recomend working from versions between 1.08-1.11 as these have been tested and I am aware of some architectual changes in ONOS which might affect this.
