### ISSUE TITLE
ISSUE IN SCRIPT TENNISON_INSTALLER.SH

### ISSUE THREAD

**Issue by KAMRANMEHBOOB** [SDN-Security/TENNISON#5]
In the script, from line number 20 to 24, the system shows that it could not read from remote repository. 
20.    git clone git@d31-git.lancaster.ac.uk:tennison/topology.git
21.    git clone git@d31-git.lancaster.ac.uk:tennison/onos.git
22.    git clone git@d31-git.lancaster.ac.uk:tennison/coordinator.git
23.    git clone git@d31-git.lancaster.ac.uk:tennison/onos-tennison-apps.git
24.    git clone git@d31-git.lancaster.ac.uk:tennison/pig-relay.git

**Comment by lyndon160** [comment]
This issue was closed. Did you resolve the issue?
