### ISSUE TITLE
Problems to start TENNISON

### ISSUE THREAD

**Issue by YR159753** [SDN-Security/TENNISON#8]
![5](https://user-images.githubusercontent.com/60662822/73763706-cc0ae800-473f-11ea-8226-417bc00844ad.png)

**Comment by lyndon160** [comment]
Hi,

It looks like the package colorama is not installed. This can be installed with the python package tool 'pip'

**Comment by YR159753** [comment]
![9](https://user-images.githubusercontent.com/60662822/73955809-f391ba00-48d1-11ea-959e-d3102689318d.png)
I installed it and it still doesn't work. Is there any additional configuration that I'm missing ?
Thanks,
Raul Ysa

**Comment by YR159753** [comment]
![9](https://user-images.githubusercontent.com/60662822/73956207-9cd8b000-48d2-11ea-9501-fa37b3daad1b.png)

**Comment by YR159753** [comment]
I solved it . I needed to use the following command: sudo apt-get install -y python-colorama

**Comment by YR159753** [comment]
Thanks for your answer, Mr. Fawcett

**Comment by mahmoud-houri** [comment]
hello:

I have the below error when I tried to run tennison experimenter

ERROR: Please shut down the controller which is running on port 6653:
