### ISSUE TITLE
ERROR: ONOS node alpha_c1 has died

### ISSUE THREAD

**Issue by YR159753** [SDN-Security/TENNISON#9]
Good afternoon,sir, one question , could you help me with this error,please.
![13](https://user-images.githubusercontent.com/60662822/74094544-fe567580-4ab0-11ea-8b29-408d796c7662.png)

**Comment by YR159753** [comment]
It worked in the first try but now that error is shown.

**Comment by lyndon160** [comment]
This is an ONOS issue. It is normally related to a lack of resources on the machine.

**Comment by YR159753** [comment]
Good afternoon, sir, I have a couple of questions
Do I have to increase the RAM in the VM ?
Is there another way to activate the TENNISON framework ? (I read the guide but it mentions vagrant)
Thanks,
Raul Ysa

**Comment by lyndon160** [comment]
The tennison framework can be ran on its own. You can edit and read that script to see how. 

Also I think one of the other closed issues under this got repo tells you how to run ONOS with one instance instead of three.

For the script you're currently running you need at least 20GB ram allocated to the VM.

**Comment by YR159753** [comment]
I increased the assigned RAM and it works.
![14](https://user-images.githubusercontent.com/60662822/74109528-39f54c00-4b52-11ea-814e-ee04794c4eea.png)
How can I use the Tennison GUI ?
Thanks, sir , for your answer :D

**Comment by YR159753** [comment]
I couldn't find that instance , is the Tennison_installer.sh ?
![15](https://user-images.githubusercontent.com/60662822/74161566-21863f80-4bed-11ea-8fea-d0d92127ffb8.png)
Thanks,
Raul Ysa

**Comment by YR159753** [comment]
I wanted to use the GUI , "GUI can be reached on IP:Port/ (127.0.0.1:5000)/

Default admin login is tennison:rocks" , is this correct?
